//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiWindowsForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuiWindowsForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap academico_72x72 {
            get {
                object obj = ResourceManager.GetObject("academico_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap academico_73x72 {
            get {
                object obj = ResourceManager.GetObject("academico_73x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap academico_73x72_hover {
            get {
                object obj = ResourceManager.GetObject("academico_73x72_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adicionar {
            get {
                object obj = ResourceManager.GetObject("adicionar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adicionar_final_32x32 {
            get {
                object obj = ResourceManager.GetObject("adicionar_final_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adicionar1 {
            get {
                object obj = ResourceManager.GetObject("adicionar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dados_72x72 {
            get {
                object obj = ResourceManager.GetObject("dados_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dados_73x74 {
            get {
                object obj = ResourceManager.GetObject("dados_73x74", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dados_73x74_hover {
            get {
                object obj = ResourceManager.GetObject("dados_73x74_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap financeiro_72x72 {
            get {
                object obj = ResourceManager.GetObject("financeiro_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap financeiro_73x60 {
            get {
                object obj = ResourceManager.GetObject("financeiro_73x60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap financeiro_73x60_hover {
            get {
                object obj = ResourceManager.GetObject("financeiro_73x60_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_aluno_142x113 {
            get {
                object obj = ResourceManager.GetObject("icone_aluno_142x113", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_aluno_142x113_hover {
            get {
                object obj = ResourceManager.GetObject("icone_aluno_142x113_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_aluno_142x115 {
            get {
                object obj = ResourceManager.GetObject("icone_aluno_142x115", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_aluno_142x115_over {
            get {
                object obj = ResourceManager.GetObject("icone_aluno_142x115_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_cadastrar {
            get {
                object obj = ResourceManager.GetObject("icone_cadastrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_cadastrar1 {
            get {
                object obj = ResourceManager.GetObject("icone_cadastrar1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_cadastrar2 {
            get {
                object obj = ResourceManager.GetObject("icone_cadastrar2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_desconectar {
            get {
                object obj = ResourceManager.GetObject("icone_desconectar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_prof_142x113 {
            get {
                object obj = ResourceManager.GetObject("icone_prof_142x113", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_prof_142x113_hover {
            get {
                object obj = ResourceManager.GetObject("icone_prof_142x113_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_prof_142x115 {
            get {
                object obj = ResourceManager.GetObject("icone_prof_142x115", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_prof_142x115_over {
            get {
                object obj = ResourceManager.GetObject("icone_prof_142x115_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icons7897 {
            get {
                object obj = ResourceManager.GetObject("icons7897", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap injecao_72x72 {
            get {
                object obj = ResourceManager.GetObject("injecao_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap injecao_73x73 {
            get {
                object obj = ResourceManager.GetObject("injecao_73x73", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap injecao_73x73_hover {
            get {
                object obj = ResourceManager.GetObject("injecao_73x73_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap modelo_tela {
            get {
                object obj = ResourceManager.GetObject("modelo-tela", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap modelo_tela_azul {
            get {
                object obj = ResourceManager.GetObject("modelo tela-azul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap modelo_tela_iconemenor {
            get {
                object obj = ResourceManager.GetObject("modelo tela-iconemenor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap modelo_tela_iconemenor1 {
            get {
                object obj = ResourceManager.GetObject("modelo tela-iconemenor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok_final_32x32 {
            get {
                object obj = ResourceManager.GetObject("ok_final_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok_menor {
            get {
                object obj = ResourceManager.GetObject("ok_menor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap responsavel_72x72 {
            get {
                object obj = ResourceManager.GetObject("responsavel_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap responsavel_73x66 {
            get {
                object obj = ResourceManager.GetObject("responsavel_73x66", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap responsavel_73x66_hover {
            get {
                object obj = ResourceManager.GetObject("responsavel_73x66_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search_76x76 {
            get {
                object obj = ResourceManager.GetObject("Search_76x76", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search_76x761 {
            get {
                object obj = ResourceManager.GetObject("Search_76x761", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap seta_voltar {
            get {
                object obj = ResourceManager.GetObject("seta_voltar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap voltar_final_32x32 {
            get {
                object obj = ResourceManager.GetObject("voltar_final_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap webdev_ok_76x76 {
            get {
                object obj = ResourceManager.GetObject("webdev-ok-76x76", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap webdev_ok_76x761 {
            get {
                object obj = ResourceManager.GetObject("webdev-ok-76x761", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
