//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiWindowsForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuiWindowsForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap academico_73x72 {
            get {
                object obj = ResourceManager.GetObject("academico_73x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap academico_73x72_disabled {
            get {
                object obj = ResourceManager.GetObject("academico_73x72_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap academico_73x72_disabled_h {
            get {
                object obj = ResourceManager.GetObject("academico_73x72_disabled_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap academico_73x72_hover {
            get {
                object obj = ResourceManager.GetObject("academico_73x72_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_matricula_47x49 {
            get {
                object obj = ResourceManager.GetObject("add_matricula_47x49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_matricula_47x49_hover {
            get {
                object obj = ResourceManager.GetObject("add_matricula_47x49_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_matricula_73x73 {
            get {
                object obj = ResourceManager.GetObject("add_matricula_73x73", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adicionar_final_32x32 {
            get {
                object obj = ResourceManager.GetObject("adicionar_final_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alterar_branco {
            get {
                object obj = ResourceManager.GetObject("alterar_branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alterar_final {
            get {
                object obj = ResourceManager.GetObject("alterar_final", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap atividade_mais {
            get {
                object obj = ResourceManager.GetObject("atividade_mais", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_add_atividade_48x48 {
            get {
                object obj = ResourceManager.GetObject("btn_add_atividade_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_add_atividade_48x48_hover {
            get {
                object obj = ResourceManager.GetObject("btn_add_atividade_48x48_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_imprimir_48x48 {
            get {
                object obj = ResourceManager.GetObject("btn_imprimir_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_imprimir_48x48_hover {
            get {
                object obj = ResourceManager.GetObject("btn_imprimir_48x48_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_ok_cadastrar_110x52 {
            get {
                object obj = ResourceManager.GetObject("btn_ok_cadastrar_110x52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_ok_cadastrar_145x52 {
            get {
                object obj = ResourceManager.GetObject("btn_ok_cadastrar_145x52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_acesso_64x80 {
            get {
                object obj = ResourceManager.GetObject("conf_acesso_64x80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_acesso_64x80_disabled {
            get {
                object obj = ResourceManager.GetObject("conf_acesso_64x80_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_acesso_64x80_hover {
            get {
                object obj = ResourceManager.GetObject("conf_acesso_64x80_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_atividades_84x75 {
            get {
                object obj = ResourceManager.GetObject("conf_atividades_84x75", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_atividades_84x75_disabled {
            get {
                object obj = ResourceManager.GetObject("conf_atividades_84x75_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_atividades_84x75_disabled_h {
            get {
                object obj = ResourceManager.GetObject("conf_atividades_84x75_disabled_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_atividades_84x75_hover {
            get {
                object obj = ResourceManager.GetObject("conf_atividades_84x75_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_desconto_79x80 {
            get {
                object obj = ResourceManager.GetObject("conf_desconto_79x80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_desconto_79x80_disabled {
            get {
                object obj = ResourceManager.GetObject("conf_desconto_79x80_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_desconto_79x80_disabled_h {
            get {
                object obj = ResourceManager.GetObject("conf_desconto_79x80_disabled_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_desconto_79x80_hover {
            get {
                object obj = ResourceManager.GetObject("conf_desconto_79x80_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_mais {
            get {
                object obj = ResourceManager.GetObject("conf_mais", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_menos {
            get {
                object obj = ResourceManager.GetObject("conf_menos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_serie_64x70 {
            get {
                object obj = ResourceManager.GetObject("conf_serie_64x70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_serie_64x70_disabled {
            get {
                object obj = ResourceManager.GetObject("conf_serie_64x70_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_serie_64x70_disabled_h {
            get {
                object obj = ResourceManager.GetObject("conf_serie_64x70_disabled_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap conf_serie_64x70_hover {
            get {
                object obj = ResourceManager.GetObject("conf_serie_64x70_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configuracoes_137x101 {
            get {
                object obj = ResourceManager.GetObject("configuracoes_137x101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configuracoes_137x101_hover {
            get {
                object obj = ResourceManager.GetObject("configuracoes_137x101_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dados_73x74 {
            get {
                object obj = ResourceManager.GetObject("dados_73x74", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dados_73x74_disabled {
            get {
                object obj = ResourceManager.GetObject("dados_73x74_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dados_73x74_disabled_h {
            get {
                object obj = ResourceManager.GetObject("dados_73x74_disabled_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dados_73x74_hover {
            get {
                object obj = ResourceManager.GetObject("dados_73x74_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap financeiro_73x60 {
            get {
                object obj = ResourceManager.GetObject("financeiro_73x60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap financeiro_73x60_disabled {
            get {
                object obj = ResourceManager.GetObject("financeiro_73x60_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap financeiro_73x60_disabled_h {
            get {
                object obj = ResourceManager.GetObject("financeiro_73x60_disabled_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap financeiro_73x60_hover {
            get {
                object obj = ResourceManager.GetObject("financeiro_73x60_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap financeiro_busca_73x75 {
            get {
                object obj = ResourceManager.GetObject("financeiro_busca_73x75", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap financeiro_busca_73x75_hover {
            get {
                object obj = ResourceManager.GetObject("financeiro_busca_73x75_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap financeiro_gnd_120x110 {
            get {
                object obj = ResourceManager.GetObject("financeiro_gnd_120x110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap financeiro_gnd_120x110_png_hover {
            get {
                object obj = ResourceManager.GetObject("financeiro_gnd_120x110_png_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap financeiro_impressora_51x53 {
            get {
                object obj = ResourceManager.GetObject("financeiro_impressora_51x53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap financeiro_impressora_51x53_hover {
            get {
                object obj = ResourceManager.GetObject("financeiro_impressora_51x53_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap func_dados_71x62 {
            get {
                object obj = ResourceManager.GetObject("func_dados_71x62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap func_dados_71x62_disabled {
            get {
                object obj = ResourceManager.GetObject("func_dados_71x62_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap func_dados_71x62_disabled_h {
            get {
                object obj = ResourceManager.GetObject("func_dados_71x62_disabled_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap func_dados_71x62_hover {
            get {
                object obj = ResourceManager.GetObject("func_dados_71x62_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap func_imprimir_50x50 {
            get {
                object obj = ResourceManager.GetObject("func_imprimir_50x50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap func_imprimir_50x50_hover {
            get {
                object obj = ResourceManager.GetObject("func_imprimir_50x50_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap func_profissional_64x71 {
            get {
                object obj = ResourceManager.GetObject("func_profissional_64x71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap func_profissional_64x71_disabled {
            get {
                object obj = ResourceManager.GetObject("func_profissional_64x71_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap func_profissional_64x71_disabled_h {
            get {
                object obj = ResourceManager.GetObject("func_profissional_64x71_disabled_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap func_profissional_64x71_hover {
            get {
                object obj = ResourceManager.GetObject("func_profissional_64x71_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_aluno_142x113 {
            get {
                object obj = ResourceManager.GetObject("icone_aluno_142x113", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_aluno_142x113_disabled {
            get {
                object obj = ResourceManager.GetObject("icone_aluno_142x113_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_aluno_142x113_hover {
            get {
                object obj = ResourceManager.GetObject("icone_aluno_142x113_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_desconectar {
            get {
                object obj = ResourceManager.GetObject("icone_desconectar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_prof_142x113 {
            get {
                object obj = ResourceManager.GetObject("icone_prof_142x113", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_prof_142x113_disabled {
            get {
                object obj = ResourceManager.GetObject("icone_prof_142x113_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_prof_142x113_hover {
            get {
                object obj = ResourceManager.GetObject("icone_prof_142x113_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap injecao_73x73 {
            get {
                object obj = ResourceManager.GetObject("injecao_73x73", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap injecao_73x73_disabled {
            get {
                object obj = ResourceManager.GetObject("injecao_73x73_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap injecao_73x73_disabled_h {
            get {
                object obj = ResourceManager.GetObject("injecao_73x73_disabled_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap injecao_73x73_hover {
            get {
                object obj = ResourceManager.GetObject("injecao_73x73_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mais_branco {
            get {
                object obj = ResourceManager.GetObject("mais_branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap matricula_68x69 {
            get {
                object obj = ResourceManager.GetObject("matricula_68x69", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap matricula_68x69_disabled {
            get {
                object obj = ResourceManager.GetObject("matricula_68x69_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap matricula_68x69_disabled_h {
            get {
                object obj = ResourceManager.GetObject("matricula_68x69_disabled_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap matricula_68x69_hover {
            get {
                object obj = ResourceManager.GetObject("matricula_68x69_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menos_branco {
            get {
                object obj = ResourceManager.GetObject("menos_branco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap modelo_tela {
            get {
                object obj = ResourceManager.GetObject("modelo-tela", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok_32x32_tipo2_final {
            get {
                object obj = ResourceManager.GetObject("ok_32x32_tipo2_final", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok_final_32x32 {
            get {
                object obj = ResourceManager.GetObject("ok_final_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap responsavel_73x66 {
            get {
                object obj = ResourceManager.GetObject("responsavel_73x66", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap responsavel_73x66_disabled {
            get {
                object obj = ResourceManager.GetObject("responsavel_73x66_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap responsavel_73x66_disabled_h {
            get {
                object obj = ResourceManager.GetObject("responsavel_73x66_disabled_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap responsavel_73x66_hover {
            get {
                object obj = ResourceManager.GetObject("responsavel_73x66_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search_32x32_final {
            get {
                object obj = ResourceManager.GetObject("Search_32x32_final", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search_76x76 {
            get {
                object obj = ResourceManager.GetObject("Search_76x76", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap simbolo_colegio {
            get {
                object obj = ResourceManager.GetObject("simbolo_colegio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vincular_final {
            get {
                object obj = ResourceManager.GetObject("vincular_final", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap voltar_final_32x32 {
            get {
                object obj = ResourceManager.GetObject("voltar_final_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap webdev_ok_76x76 {
            get {
                object obj = ResourceManager.GetObject("webdev-ok-76x76", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap webdev_ok_76x761 {
            get {
                object obj = ResourceManager.GetObject("webdev-ok-76x761", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
